# Generated by Django 5.0.6 on 2024-05-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=100)),
                ('people', models.CharField(max_length=100)),
                ('emotion', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mood_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
