# Generated by Django 5.0.6 on 2024-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodentry',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='emotion',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='emotions',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mood_images/'),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='people',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='weather',
            field=models.CharField(max_length=20),
        ),
    ]
