# Generated by Django 5.0.6 on 2024-05-10 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_created_at_moodentry_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
