# Generated by Django 5.0.6 on 2024-05-10 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_moodentry_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodentry',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='emotions',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='notes',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='people',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='weather',
            field=models.CharField(max_length=100),
        ),
    ]
